### ISSUE TITLE
Change license from GPL to MIT/X11 or zlib (or anything else, honestly)

### ISSUE THREAD

**Issue by karai17** [davisdude/mlib#11]
GPL is a very restrictive license, especially for a math library. GPL licensing effectively makes this library unusable in any case where the program needs to be compiled. Consider fused LOVE games, for instance. It is also worth noting that GPL effects the whole project. This is not very friendly for a general purpose library.

I highly recommend changing the license to something less restrictive such as my personal license of choice, MIT/X11, or LOVE's own zlib license.

Edit: FULL DISCLOSURE: We want to adapt some parts of your code to fit into our own math library, CPML. But even that aside, because of the GPL license we would not be able to use this code in any of our projects.

**Comment by davisdude** [comment]
I hadn't ever really considered that... I'll fix that ASAP

**Comment by davisdude** [comment]
Let me know what you use it for in CPML!
