### ISSUE TITLE
mlib.subtract is exported, but nil -- subtractVector isn't defined

### ISSUE THREAD

**Issue by idbrii** [davisdude/mlib#14]
mlib exports a function that isn't defined:

```lua
	vec2 = {
        -- ...

        -- Aliases
        copy = cloneVector,
        subtract = subtractVector,  -- <-----
        multiply = mulVector,
        -- ...
	},
}
```

subtractVector is not defined in the file.

https://github.com/davisdude/mlib/blob/master/mlib.lua#L1397

I only noticed because [luacheck](https://github.com/mpeterv/luacheck) caught it. Removing the export is fine by me.

**Comment by davisdude** [comment]
Thanks for catching this! It should be fixed now - let me know if it's still causing issues.
