### ISSUE TITLE
Potential Bug in removeDuplicatePointsFlat.

### ISSUE THREAD

**Issue by Tourahi** [davisdude/mlib#17]
in removeDuplicatePointsFlat you can see that the first for loop is defined as such : 
`for i = #tab, 1 -2 do`
Did you mean for it to translate to : 
`for i = #t, 1, -1 do`
or you just forgot the ',' between 1 and -2 ?

**Comment by davisdude** [comment]
Huh, you would be right. It took this long to notice because it never affected behavior (the `if i ~= ii` check ensures that only "odd," valid indices are checked). Thanks for pointing this out, and good eye!
